services:
  mongodb:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=malak
      - MONGO_INITDB_ROOT_PASSWORD=malak
  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=malak
      - ME_CONFIG_MONGODB_ADMINPASSWORD=malak
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}